### ISSUE TITLE
How to configure the CakePHP site as a SP ?

### ISSUE THREAD

**Issue by saulojg** [zl4bv/CakePHP-simpleSAMLphp-Plugin#4]
Could you please provide an example showing how to add the CakePHP site as a SP on the simpleSAMLphp configuration? I'm struggling with the SingleSignOnService and SingleLogoutService URLs

I configured a SimpleSamlPHP working as a IDP
On the CakePHP site (the SP) I'm using both SimpleSamlPHP and Auth->FormAuthenticate

Thanks in advance

**Comment by zl4bv** [comment]
For the logout URL, you could create an action in your cake controller to call the logout function:

public function logout() {
    return $this->redirect($this->Auth->logout());
}

Assuming you're using the SamlFormAuthenticate, this will invoke simpleSAMLphp's logout mechanism for you. If simpleSAMLphp is configured with a logout redirect URL then the user will be redirected to this URL prior to being logged out.

As for the sign on URL, I will need to dig into simpleSAMLphp's code a bit more to answer this for you.
