### ISSUE TITLE
SamlFormAuthenticate doesn't load settings

### ISSUE THREAD

**Issue by saulojg** [zl4bv/CakePHP-simpleSAMLphp-Plugin#5]
SamlFormAuthenticate isn't properly loading settings such as userModel

Apparently, SamlFormAuthenticate->_construct lacks a call to parent::__construct($collection, $settings);

**Comment by zl4bv** [comment]
I will look into fixing this within the next week. However, if you've already fixed this in your code then I encourage you to submit a pull request.
